export const data = {
  record: {
    spoken: [
      {
        speaker: "agent",
        startTimestamp: 41,
        endTimestamp: 50,
        text: "I understand. That's better not Uh, kind of quality. We guarantee our customer. Do you have the model number and it was J Days handy.",
        decibelLevels: {
          41: "82.59 dB",
          42: "82.28 dB",
          43: "81.16 dB",
          44: "80.75 dB",
          45: "80.47 dB",
          46: "83.54 dB",
          47: "82.8 dB",
          48: "80.57 dB",
          49: "84.6 dB",
          50: "80.74 dB",
        },
        segmentNumber: 5,
        sentiment: "positive",
      },
      {
        speaker: "agent",
        startTimestamp: 51,
        endTimestamp: 53,
        text: "Iron them to proceed. What your complaint.",
        decibelLevels: {
          51: "80.74 dB",
          52: "82.72 dB",
          53: "79.44 dB",
        },
        segmentNumber: 6,
        sentiment: "negative",
      },
      {
        speaker: "customer",
        startTimestamp: 56,
        endTimestamp: 64,
        text: "Model. What Sorry. I didn't hear B l 1234 something. Just put yourself with John yesterday. Sorry. Check your system for them.",
        decibelLevels: {
          56: "70.86 dB",
          57: "88.12 dB",
          58: "88.12 dB",
          59: "87.28 dB",
          60: "80.91 dB",
          61: "76.27 dB",
          62: "77.49 dB",
          63: "79.18 dB",
          64: "76.61 dB",
        },
        segmentNumber: 7,
        sentiment: "negative",
      },
      {
        speaker: "agent",
        startTimestamp: 540,
        endTimestamp: 548,
        text: "Model. What Sorry. I didn't hear B l 1234 something. Just put yourself with John yesterday. Sorry. Check your system for them.",
        decibelLevels: {
          540: "70.86 dB",
          541: "88.12 dB",
          542: "88.12 dB",
          543: "87.28 dB",
          544: "80.91 dB",
          545: "76.27 dB",
          546: "77.49 dB",
          547: "79.18 dB",
          548: "76.61 dB",
        },
        segmentNumber: 9,
        sentiment: "negative",
      },
    ],
    outCome: {
      speaker: "agent",
      startTimestamp: 89,
      text: "We're arrange for a replacement for to be sent out to you immediately",
      sentiment: "positive",
    },
    durationSeconds: 240,
    issueDetected: 88,
  },
};
